### PR TITLE
Upgrading to JTS 1.17.0

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by halset** [comment]
Thank you for your good work on JTS - the most essential java lib for us geo nerds.

**Comment by jodygarnett** [comment]
Excellent, please let us know when the next release is out for geotools / geoserver to depend on.

**Comment by halset** [comment]
1.3.9 has been released

**Comment by jnh5y** [comment]
@halset thanks for merging my PR and cutting the release.  I've asked @jodygarnett to build and post it to the OSGeo maven repository. 

Shout if you have the jars available elsewhere!

**Comment by jodygarnett** [comment]
Thank you, I built that tag locally and uploaded to repo.osgeo.org [here](https://repo.osgeo.org/#browse/search=keyword%3D%22no%2Fecc%2Fvectortile%2Fjava-vector-tile%2F1.3.9%22:bb6c6ef9796dac83350745ac43f639a6).

I could not get the javadocs to build.

**Comment by halset** [comment]
@jodygarnett As mentioned in the [README.md](https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/README.md), the build are published to https://maven.ecc.no/releases.

**Comment by jodygarnett** [comment]
Thanks, I will try and set it up so that osgeo repo caches from `https://maven.ecc.no/releases` (rather than republishes).

**Comment by halset** [comment]
@jodygarnett release 1.3.10 has a fix for javadoc as well

**Pull request merged**
