### PR TITLE
Upgraded to JTS 1.15.0.

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Hi all, we are working on upgrading GeoTools and GeoServer to use JTS 1.15.0, and this project is used by a GeoServer module.

Is the JTS version upgrade acceptable?  And if so, would it be possible to merge and cut a release?

**Comment by halset** [comment]
@jnh5y Thank you! I will merge and then create a new release.

**Comment by halset** [comment]
@jnh5y I released version 1.3.0 with this fix. Hope it works fine and thank you!

**Comment by halset** [comment]
@jnh5y Thank you for the help! Can you try v1.3.1?

**Pull request merged**
